In [49]:

import numpy as np
import pandas as pd
data=pd.read_csv(r"C:\Users\rajes\Downloads\archive (2)\Messy_Employee_dataset.csv")
print(data)

     Employee_ID First_Name Last_Name   Age   Department_Region    Status  \
0        EMP1000        Bob     Davis  25.0   DevOps-California    Active
1        EMP1001        Bob     Brown   NaN       Finance-Texas    Active
2        EMP1002      Alice     Jones   NaN        Admin-Nevada   Pending
3        EMP1003        Eva     Davis  25.0        Admin-Nevada  Inactive
4        EMP1004      Frank  Williams  25.0  Cloud Tech-Florida    Active
...          ...        ...       ...   ...                 ...       ...
1015     EMP2015      David    Miller  30.0       HR-California    Active
1016     EMP2016      David   Johnson  30.0    Cloud Tech-Texas  Inactive
1017     EMP2017    Charlie  Williams  40.0    Finance-New York    Active
1018     EMP2018      Alice    Garcia  30.0          HR-Florida  Inactive
1019     EMP2019      Heidi     Jones  30.0     DevOps-Illinois   Pending

       Join_Date     Salary                         Email       Phone  \
0       4/2/2021   59767.65         bob.davis@example.com -1651623197
1      7/10/2020   65304.66         bob.brown@example.com -1898471390
2      12/7/2023   88145.90       alice.jones@example.com -5596363211
3     11/27/2021   69450.99         eva.davis@example.com -3476490784
4       1/5/2022  109324.61    frank.williams@example.com -1586734256
...          ...        ...                           ...         ...
1015   8/19/2023        NaN      david.miller@example.com -3546212759
1016   11/7/2021  100215.06     david.johnson@example.com -2508261122
1017   10/4/2023  114587.11  charlie.williams@example.com -1261632487
1018  12/16/2024   71318.79      alice.garcia@example.com -8995729892
1019   2/22/2021   77764.24       heidi.jones@example.com -7629745492

     Performance_Score  Remote_Work
0              Average         True
1            Excellent         True
2                 Good         True
3                 Good         True
4                 Poor        False
...                ...          ...
1015              Good         True
1016              Good         True
1017           Average        False
1018              Good         True
1019           Average        False

[1020 rows x 12 columns]

In [50]:
# to see first 5 records
data.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [51]:
# to check the information of dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

In [52]:
# to check the stastical info for numerical attributes
data.describe()

              Age         Salary         Phone
count  809.000000     996.000000  1.020000e+03
mean    32.484549   85155.056396 -4.942253e+09
std      5.656860   19873.727918  2.817326e+09
min     25.000000   50047.320000 -9.994973e+09
25%     25.000000   68392.487500 -7.341992e+09
50%     30.000000   85547.870000 -4.943997e+09
75%     40.000000  100974.027500 -2.520391e+09
max     40.000000  119971.650000 -3.896086e+06

In [54]:
# to check the missing values
data.isnull().sum()

#from the data set age and salary has missing values

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

In [55]:
#to check the duplicate values
data.duplicated().sum()

# there is no duplicate values

np.int64(0)

In [58]:
# to handel the missing values
data["Age"]=data["Age"].fillna(data["Age"].mean())
data["Salary"]=data["Salary"].fillna(data["Salary"].mean())
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                1020 non-null   float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             1020 non-null   float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

In [77]:
#to create a new column
current_year=pd.Timestamp.today().year
data["Birth_year"]=current_year -data["Age"]
print(data)

     Employee_ID First_Name Last_Name        Age   Department_Region  \
0        EMP1000        Bob     Davis  25.000000   DevOps-California
1        EMP1001        Bob     Brown  32.484549       Finance-Texas
2        EMP1002      Alice     Jones  32.484549        Admin-Nevada
3        EMP1003        Eva     Davis  25.000000        Admin-Nevada
4        EMP1004      Frank  Williams  25.000000  Cloud Tech-Florida
...          ...        ...       ...        ...                 ...
1015     EMP2015      David    Miller  30.000000       HR-California
1016     EMP2016      David   Johnson  30.000000    Cloud Tech-Texas
1017     EMP2017    Charlie  Williams  40.000000    Finance-New York
1018     EMP2018      Alice    Garcia  30.000000          HR-Florida
1019     EMP2019      Heidi     Jones  30.000000     DevOps-Illinois

        Status   Join_Date         Salary                         Email  \
0       Active    4/2/2021   59767.650000         bob.davis@example.com
1       Active   7/10/2020   65304.660000         bob.brown@example.com
2      Pending   12/7/2023   88145.900000       alice.jones@example.com
3     Inactive  11/27/2021   69450.990000         eva.davis@example.com
4       Active    1/5/2022  109324.610000    frank.williams@example.com
...        ...         ...            ...                           ...
1015    Active   8/19/2023   85155.056396      david.miller@example.com
1016  Inactive   11/7/2021  100215.060000     david.johnson@example.com
1017    Active   10/4/2023  114587.110000  charlie.williams@example.com
1018  Inactive  12/16/2024   71318.790000      alice.garcia@example.com
1019   Pending   2/22/2021   77764.240000       heidi.jones@example.com

           Phone Performance_Score  Remote_Work   Birth_year
0    -1651623197           Average         True  2001.000000
1    -1898471390         Excellent         True  1993.515451
2    -5596363211              Good         True  1993.515451
3    -3476490784              Good         True  2001.000000
4    -1586734256              Poor        False  2001.000000
...          ...               ...          ...          ...
1015 -3546212759              Good         True  1996.000000
1016 -2508261122              Good         True  1996.000000
1017 -1261632487           Average        False  1986.000000
1018 -8995729892              Good         True  1996.000000
1019 -7629745492           Average        False  1996.000000

[1020 rows x 13 columns]

In [79]:
data.to_csv("final_cleaned_dataset.csv", index=False)

In [80]:
import os
os.listdir()

['.ipynb_checkpoints', 'final_cleaned_dataset.csv', 'TASK1.ipynb']